using System.Text.RegularExpressions;

namespace DevToolkit.Services.Har;

public enum IntermediaryKind
{
    Proxy,
    Edge
}

/// <summary>Matches a response header by name and, optionally, value.</summary>
public sealed record HeaderRule(string Name, string? ValuePattern = null)
{
    private readonly Regex? _value = ValuePattern is null ? null : new Regex(ValuePattern, RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

    public string? Match(HarEntry entry)
    {
        foreach (var header in entry.ResponseHeaders)
        {
            if (header.Name.Equals(Name, StringComparison.OrdinalIgnoreCase) && (_value is null || _value.IsMatch(header.Value)))
            {
                return $"{header.Name}: {Truncate(header.Value)}";
            }
        }

        return null;
    }

    private static string Truncate(string value) => value.Length > 60 ? value[..60] + "…" : value;
}

/// <summary>
/// Fingerprint of a proxy, CDN or WAF. <see cref="Presence"/> rules show traffic passes through it;
/// <see cref="Block"/> rules show a response was generated by it rather than the target server.
/// </summary>
public sealed class IntermediarySignature
{
    public required string Vendor { get; init; }
    public required IntermediaryKind Kind { get; init; }
    public IReadOnlyList<HeaderRule> Presence { get; init; } = [];
    public IReadOnlyList<HeaderRule> BlockHeaders { get; init; } = [];
    public IReadOnlyList<string> BlockBodyPatterns { get; init; } = [];
    public IReadOnlyList<string> RedirectHostPatterns { get; init; } = [];

    private Regex[]? _body;
    private Regex[]? _redirect;

    public string? MatchPresence(HarEntry entry) => Presence.Select(r => r.Match(entry)).FirstOrDefault(m => m is not null);

    public string? MatchBlock(HarEntry entry)
    {
        foreach (var rule in BlockHeaders)
        {
            if (rule.Match(entry) is { } header)
            {
                return $"response header {header}";
            }
        }

        if (entry.RedirectTarget is { } target && Uri.TryCreate(target, UriKind.Absolute, out var uri))
        {
            _redirect ??= RedirectHostPatterns.Select(Compile).ToArray();
            if (_redirect.Any(r => r.IsMatch(uri.Host)))
            {
                return $"redirect to {uri.Host}";
            }
        }

        _body ??= BlockBodyPatterns.Select(Compile).ToArray();
        if (_body.Length > 0)
        {
            var body = entry.GetResponseText();
            foreach (var pattern in _body)
            {
                var match = pattern.Match(body);
                if (match.Success)
                {
                    return $"response body contains \"{match.Value.Trim()}\"";
                }
            }
        }

        return null;
    }

    private static Regex Compile(string pattern) => new(pattern, RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
}

public static class HarSignatures
{
    // Host patterns are matched against the redirect target's host name
    public static readonly IReadOnlyList<IntermediarySignature> All =
    [
        new()
        {
            Vendor = "Zscaler",
            Kind = IntermediaryKind.Proxy,
            BlockHeaders = [new("Server", "zscaler")],
            BlockBodyPatterns = [@"zscaler"],
            RedirectHostPatterns = [@"(^|\.)zscaler(one|two|three|beta|gov)?\.net$", @"(^|\.)zscloud\.net$", @"(^|\.)zscalergov\.net$"]
        },
        new()
        {
            Vendor = "Netskope",
            Kind = IntermediaryKind.Proxy,
            BlockHeaders = [new("Server", "netskope")],
            BlockBodyPatterns = [@"netskope"],
            RedirectHostPatterns = [@"(^|\.)goskope\.com$", @"(^|\.)netskope\.com$"]
        },
        new()
        {
            Vendor = "Symantec / Blue Coat ProxySG",
            Kind = IntermediaryKind.Proxy,
            Presence = [new("X-BlueCoat-Via"), new("Via", "bluecoat|proxysg")],
            BlockBodyPatterns = [@"blue\s?coat", @"symantec web (security|gateway)"]
        },
        new()
        {
            Vendor = "Forcepoint / Websense",
            Kind = IntermediaryKind.Proxy,
            Presence = [new("Via", "websense|forcepoint")],
            BlockBodyPatterns = [@"websense", @"forcepoint"]
        },
        new()
        {
            Vendor = "Cisco Umbrella",
            Kind = IntermediaryKind.Proxy,
            BlockHeaders = [new("Server", "umbrella|opendns")],
            BlockBodyPatterns = [@"cisco umbrella", @"opendns"],
            RedirectHostPatterns = [@"(^|\.)opendns\.com$", @"(^|\.)umbrella\.com$"]
        },
        new()
        {
            Vendor = "Palo Alto Networks",
            Kind = IntermediaryKind.Proxy,
            BlockBodyPatterns = [@"palo\s?alto networks"]
        },
        new()
        {
            Vendor = "Squid",
            Kind = IntermediaryKind.Proxy,
            Presence = [new("Via", "squid"), new("X-Cache", "squid")],
            BlockHeaders = [new("X-Squid-Error"), new("Server", "^squid")]
        },
        new()
        {
            Vendor = "Cloudflare",
            Kind = IntermediaryKind.Edge,
            Presence = [new("CF-RAY"), new("Server", "^cloudflare")],
            BlockHeaders = [new("cf-mitigated")],
            BlockBodyPatterns = [@"attention required! \| cloudflare", @"cloudflare ray id", @"error code: 10\d\d"]
        },
        new()
        {
            Vendor = "Akamai",
            Kind = IntermediaryKind.Edge,
            Presence = [new("Server", "akamai"), new("X-Akamai-Transformed")],
            BlockBodyPatterns = [@"reference\s?#\d+\.[0-9a-f]+\.\d+\.[0-9a-f]+"]
        },
        new()
        {
            Vendor = "AWS CloudFront",
            Kind = IntermediaryKind.Edge,
            Presence = [new("X-Amz-Cf-Id"), new("Via", "cloudfront")],
            BlockBodyPatterns = [@"generated by cloudfront", @"request blocked\. we can't connect to the server"]
        },
        new()
        {
            Vendor = "AWS API Gateway",
            Kind = IntermediaryKind.Edge,
            Presence = [new("x-amz-apigw-id")],
            BlockHeaders = [new("x-amzn-ErrorType")]
        },
        new()
        {
            Vendor = "Azure Front Door",
            Kind = IntermediaryKind.Edge,
            Presence = [new("X-Azure-Ref")],
            BlockBodyPatterns = [@"the request is blocked\.", @"azure front door"]
        },
        new()
        {
            Vendor = "Imperva / Incapsula",
            Kind = IntermediaryKind.Edge,
            Presence = [new("X-Iinfo"), new("X-CDN", "imperva|incapsula")],
            BlockBodyPatterns = [@"incapsula incident", @"powered by imperva"]
        },
        new()
        {
            Vendor = "F5 BIG-IP",
            Kind = IntermediaryKind.Edge,
            Presence = [new("Set-Cookie", @"^(TS01[0-9a-f]+|BIGipServer)")],
            BlockBodyPatterns = [@"the requested url was rejected\. please consult with your administrator"]
        }
    ];
}
